### ISSUE TITLE
Gaussian Splatting for ultrasound reconstruction

### ISSUE THREAD

**Issue by JishuaiZhang** [Rishit-dagli/NeRF-US#2]
Very amazing work. I have a question: how is Gaussian Splatting used for rasterization in ultrasound view synthesis?

**Comment by Rishit-dagli** [comment]
hey, so we use [`gsplat`](https://github.com/nerfstudio-project/gsplat) (running it like any of our other baselines with `nerfstudio`). we already have a [COLMAP dataset](https://huggingface.co/datasets/rishitdagli/us-in-the-wild), so we start with initializing gaussians on SfM points from COLMAP and train on full images following the `gsplat` codebase (with the hyperparameters we list in the paper).

maybe this bit wasn't clear earlier but we evaluate gaussian splatting for the standard NeRF task (some recent works have tried to do different tasks with such representation but we do not explore any other tasks), 3D reconstruction and novel view synthesis.
