### ISSUE TITLE
There are a lot of small errors in the code

### ISSUE THREAD

**Issue by Hoodie-Zhang** [Rishit-dagli/NeRF-US#3]
Very amazing work. I am very interested in your work. I have two questions.
The first question is download either the synthetic knee cubes or the synthetic phantom cubes dataset. I downloaded the dataset from the hugging face link you gave me. I found that there is no synthetic knee cubes or the synthetic phantom cubes dataset. I would like to know where this dataset(the synthetic knee cubes or the synthetic phantom cubes dataset) comes from.

The second problem is that there are many errors in your code. such as the model reference name is wrong, and the referenced model does not exist. Mainly focused on(ns-train nerfus --data path/to/data nerfstudio-data --eval-mode train-split-fraction command runtime) . For example NameError: name 'NeRFModelConfig' is not defined(I configured the environment as you requested, but the corresponding nerfstudio.models.vannila_nerf does not exist in NeRFModelConfig). I have made some modifications and solved some errors, but there are still a lot of errors. Could you please update your latest executable code?
I really hope to get your reply.

**Comment by Rishit-dagli** [comment]
thanks so much for raising this, i somehow missed this but i have a bunch of changes in my local nerfstudio clone (which is how i trained the models), for instance the psf code and the field is not here. ill get these ported to this repository in the next week or so which should be straightforward to do, just a bit of busy work 😅. thanks again for pointing this, let me reach back about this soon.

**Comment by Rishit-dagli** [comment]
fixed
